FROM node:16.16-alpine
USER root

RUN npm install -g --quiet lerna serverless esbuild firebase-tools jest 
RUN npm install -g yarn --force
RUN  apk update \
  && apk upgrade \
  && apk add ca-certificates \
  && update-ca-certificates \
  && apk add --update coreutils && rm -rf /var/cache/apk/*   \ 
  && apk add --update openjdk11 tzdata curl unzip bash \
  && apk add --no-cache nss \
  && rm -rf /var/cache/apk/*
